// Generated by gencpp from file beginner_tutorials/AI.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_AI_H
#define BEGINNER_TUTORIALS_MESSAGE_AI_H

#include <ros/service_traits.h>


#include <beginner_tutorials/AIRequest.h>
#include <beginner_tutorials/AIResponse.h>


namespace beginner_tutorials
{

struct AI
{

typedef AIRequest Request;
typedef AIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AI
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::AI > {
  static const char* value()
  {
    return "b275fc781a7750fca95a098877b3f1f6";
  }

  static const char* value(const ::beginner_tutorials::AI&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::AI > {
  static const char* value()
  {
    return "beginner_tutorials/AI";
  }

  static const char* value(const ::beginner_tutorials::AI&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::AIRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::AI >
template<>
struct MD5Sum< ::beginner_tutorials::AIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::AI >::value();
  }
  static const char* value(const ::beginner_tutorials::AIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::AIRequest> should match
// service_traits::DataType< ::beginner_tutorials::AI >
template<>
struct DataType< ::beginner_tutorials::AIRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::AI >::value();
  }
  static const char* value(const ::beginner_tutorials::AIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::AIResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::AI >
template<>
struct MD5Sum< ::beginner_tutorials::AIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::AI >::value();
  }
  static const char* value(const ::beginner_tutorials::AIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::AIResponse> should match
// service_traits::DataType< ::beginner_tutorials::AI >
template<>
struct DataType< ::beginner_tutorials::AIResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::AI >::value();
  }
  static const char* value(const ::beginner_tutorials::AIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_AI_H
